---
# tasks file for tomcat
 - name: updating repos
   include_tasks: update_repos_{{ansible_os_family}}.yaml
 - name: installing required java
   include_tasks: install_java_{{ansible_os_family}}.yaml
 - name: selecting required java
   include_tasks: select_alternatives_{{ansible_os_family}}.yaml
 - name: downloading required tomcat
   get_url:
     url: "{{tomcat_url}}"
     dest: /usr/local
 - name: extracting downloaded tomcat
   unarchive:
     src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
     dest: /usr/local
     remote_src: yes
 - name: renaming tomcat home
   command: mv /usr/local/apache-tomcat-{{req_tomcat_ver}} /usr/local/latest
   ignore_errors: True
 - name: replacing default port with required port
   template:
     src: /home/sai/server.xml.j2
     dest: /usr/local/latest/conf/server.xml
   notify:
     - stop the tomcat
 - name: copying tomcat-user.xml
   template:
     src: /home/sai/tomcat-users.xml.j2
     dest: /usr/local/latest/conf/tomcat-users.xml
 - name: copying context.xml
   template:
     src:  /home/sai/context.xml.j2
     dest: /usr/local/latest/webapps/manager/META-INF/context.xml
 - name: running tomcat
   shell: nohup /usr/local/latest/bin/startup.sh &

