---
- hosts: all
  tasks:
  - block:
    - name: installing httpd for redhat os family
      yum:
        name: httpd
        state: present
    - name: starting httpd for redhat os family
      service:
        name: httpd
        state: started
    when: ansible_os_family=="RedHat"
  - block:
    - name: installing apache2 for debain os family
      apt:
        name: apache2
        state: present
    - name: starting apache2 for debain os family
      service:
        name: apache2
        state: started
    when: ansible_os_family=="Debian"
  become: yes
