---
 - name: working with comparsion operators
   hosts: localhost
   gather_facts: false
   vars:
     - x: 10
     - y: 20
   tasks:
     - name: print messages
       debug:
         msg:
           - "value of x: {{x}} value of y: {{ y }}"
           - "x == y: {{ x == y}}"
           - "x != y: {{ x != y }}"
           - "x < y: {{ x < y }}"
           - "x > y: {{ x > y }}"
           - "x <= y: {{ x <= y }}"
           - "x >= y: {{ x >= y }}"
