---
 - name: create play1
   hosts: all
   become: yes
   tasks:
   - name: Installing webserver on RedHat family
     yum:
       name: httpd
       state: present
     when: ansible_os_family=="RedHat"
   - name: Installing webserver on Debian family
     apt:
       name: apache2
       state: present
     when: ansible_os_family=="Debian"
   - name: Installing java on RedHat family
     yum:
       name: java-1.8.0
       state: present
     when: ansible_os_family=="RedHat"
   - name: Installing java on Debian family
     apt:
       name: openjdk-8-jdk
       state: present
     when: ansible_os_family=="Debian"
