---
- name: provide sudo access
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    backup: yes
    regexp: '^{{ username }}'
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    state: present
  notify:
  - restart sshd
